S - single responsibility principle (princípio da responsabilida única)
o - open closed principle (princípio aberto fechado)
l - liskov substitution principle (princípio da substituição de liskov)
i - interface segregation principle (princípio da segregação da interface)
d - dependency inversion principle (princípio da inversão da dependência)